name: New Progress Tracker
description: Create a progress tracker for a B2AI site.
title: "[Progress Tracker]: "
body:
  - type: input
    id: site
    attributes:
      label: Data Contributing Site
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Site Main Contact
    validations: 
      required: true
  - type: textarea
    id: etl-rep
    attributes:
      label: ETL Representatives
    validations: 
      required: true
  - type: dropdown
    id: site-classification
    attributes:
      label: Site Classification
      options:
        - Started with OMOP instance
        - Started with version of CDM that can be moved 
        - Did not start with OMOP instance
    validations:
      required: true
  - type: checkboxes
    id: data-classification
    attributes:
      label: Data Classification Type?
      options:
        - label: EHR Data
        - label: Flowsheets
        - label: Waveform Data
        - label: Image Data
    # - type: markdown
    #   attributes:
    #     value: "## Site TODO:"
    # - type: checkboxes
    #   attributes:
    #     options:
    #       - label: Has data been submitted?
    # - type: input
    #   attributes:
    #     label: Date of Data Submission
    # - type: checkboxes
    #   attributes:
    #     options:
    #       - label: Has ETL been completed?
    # - type: input
    #   attributes:
    #     label: Date of ETL completion
    # - type: checkboxes
    #   attributes:
    #     options:
    #       - label: Has Data Quality Dashboard (DQD) been run on your OMOP instance?
    # - type: input
    #   attributes:
    #     label: Date of DQD run
    # - type: checkboxes
    #   attributes:
    #     options:
    #       - label: Have the Data Quality Dashboard (DQD) results been submitted?
    # - type: input
    #   attributes:
    #     label: Date of DQD results submission
    # - type: checkboxes
    #   attributes:
    #     options:
    #       - label: Has Achilles been run on your OMOP instance?
    # - type: input
    #   attributes:
    #     label: Date of Achilles run
    # - type: checkboxes
    #   attributes:
    #     options:
    #       - label: Have the Achilles results been submitted?
    # - type: input
    #   attributes:
    #     label: Date of Achilles results submission
    # - type: checkboxes
    #   attributes:
    #     options:
    #       - label: Has flowsheet data been identified?
    # - type: checkboxes
    #   attributes:
    #     options:
    #       - label: Has flowsheet format been identified?
    # - type: checkboxes
    #   attributes:
    #     options:
    #       - label: Has site begun mapping process?
    # - type: checkboxes
    #   attributes:
    #     options:
    #       - label: Has Standards Module reviewed flowsheet mappings?
