name: New Progress Tracker
description: Create a progress tracker for a B2AI site.
title: "[Progress Tracker]: "
projects: "bridge2ai/3"
body:
  - type: input
    id: site
    attributes:
      label: Data Contributing Site
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Site Main Contact
    validations: 
      required: true
  - type: textarea
    id: etl-rep
    attributes:
      label: ETL Representatives
    validations: 
      required: true
  - type: dropdown
    id: site-classification
    attributes:
      label: Site Classification
      options:
        - Started with OMOP instance
        - Started with version of CDM that can be moved 
        - Did not start with OMOP instance
    validations:
      required: true
  - type: checkboxes
    id: data-classification
    attributes:
      label: Data Classification Type?
      options:
        - label: EHR Data
        - label: Flowsheets
        - label: Waveform Data
        - label: Image Data
  - type: markdown
    attributes:
      value: "<br>"
  - type: markdown
    attributes:
      value: "# Site TODO:"
  - type: checkboxes
    attributes:
      label: Data Submission
      options:
        - label: Has data been submitted?
  - type: input
    attributes:
      label: Date of Data Submission
  - type: markdown
    attributes:
      value: "<br>"
  - type: markdown
    attributes:
      value: "## Data Mapping"
  - type: checkboxes
    attributes:
      label: Have you prioritized data for mapping?
      options:
        - label: "Yes"
        - label: "No"
  - type: checkboxes
    id: prioritize-data-mapping
    attributes:
      label: Do you have source codes that do not map to OMOP standards?
      options:
        - label: "Yes"
        - label: "No"
  - type: checkboxes
    id: unmapped-source-codes
    attributes:
      label: Do you store mapping precision metadata?
      options:
        - label: "Yes"
        - label: "No"
  - type: checkboxes
    id: mapping-precision-metadata
    attributes:
      label: ETL Completion
      options:
        - label: Has ETL been completed?
  - type: input
    attributes:
      label: Date of ETL completion
  - type: markdown
    attributes:
      value: "<br>"
  - type: checkboxes
    attributes:
      label: Data Quality Dashboard (DQD) Execution
      options:
        - label: Has Data Quality Dashboard (DQD) been run on your OMOP instance?
  - type: input
    attributes:
      label: Date of DQD run
  - type: markdown
    attributes:
      value: "<br>"
  - type: checkboxes
    attributes:
      label: Data Quality Dashboard (DQD) Submission
      options:
        - label: Have the Data Quality Dashboard (DQD) results been submitted?
  - type: input
    attributes:
      label: Date of DQD results submission
  - type: markdown
    attributes:
      value: "<br>"
  - type: checkboxes
    attributes:
      label: Achilles Execution
      options:
        - label: Has Achilles been run on your OMOP instance?
  - type: input
    attributes:
      label: Date of Achilles run
  - type: markdown
    attributes:
      value: "<br>"
  - type: checkboxes
    attributes:
      label: Achilles Submission
      options:
        - label: Have the Achilles results been submitted?
  - type: input
    attributes:
      label: Date of Achilles results submission
  - type: markdown
    attributes:
      value: "<br>"
  - type: checkboxes
    attributes:
      label: Flowsheet data
      options:
        - label: Has flowsheet data been identified?
        - label: Has flowsheet format been identified?
        - label: Has the site begun mapping process?
        - label: Has Standards Module reviewed flowsheet mappings?
